baseURL: /
languageCode: 'en-us'
title: 'Mezmo Workshops'
enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true

contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true

# Highlighting config
# This one is mutually exclusive with prism_syntax_highlighting
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: true
pygmentsStyle: monokai

services:
  googleAnalytics:
    id: G-YHBT24XG9S

taxonomies:
  tag: tags
  category: categories

params:
  taxonomy:
    taxonomyCloud:
      - tags
      - categories
    taxonomyCloudTitle:
      - Tag Cloud
      - Categories
    taxonomyPageHeader:
      - tags
      - categories

  copyright: Mezmo, Inc.
  privacy_policy: 'https://www.mezmo.com/privacy-policy'
  version_menu: Releases
  archived_version: false
  version: '1.0'
  url_latest_version: 'https://logdna.github.io/mezmo-workshops'
  github_repo: 'https://github.com/logdna/mezmo-workshops'
#  github_project_repo: 'https://github.com/logdna/mezmo-workshops'
  github_branch: main

#  gcs_engine_id: a2205c48fadd341ac
  algolia_docsearch: false
  offlineSearch: true

  # Enable syntax highlighting and copy buttons on code blocks with Prism
  # This one is mutually exclusive with pygmentsCodeFences
  prism_syntax_highlighting: false

  mermaid:
    enable: true

  plantuml:
    enable: true

  markmap:
    enable: true

  ui:
    # Set to true to disable breadcrumb navigation.
    breadcrumb_disable: false
    # Set to true to disable the About link in the site footer
    footer_about_disable: true
    # Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
    navbar_logo: true
    navbar_translucent_over_cover_disable: true
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact: true
    sidebar_menu_foldable: true
    sidebar_menu_truncate: 1000
    sidebar_cache_limit: 10

    # Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
    sidebar_search_disable: false
    feedback:
      enable: true
      'yes': >-
        Glad to hear it! Please <a
        href="https://github.com/logdna/mezmo-workshops/issues/new">tell us how we can improve</a>.
      'no': >-
        Sorry to hear that. Please <a
        href="https://github.com/logdna/mezmo-workshops/issues/new">tell us how we can improve</a>.
    readingtime:
      enable: true

#  show_banner: true

#  fonts:
#    - name: Open Sans
#      sizes: [ 300, 400, 600, 700 ]
#      type: sans_serif

  links:
    user:
      - name: Instagram
        url: 'https://instagram.com/mezmodata'
        icon: fab fa-instagram
        desc: Discussion and help from your fellow users

      - name: Twitter
        url: 'https://twitter.com/mezmodata'
        icon: fab fa-twitter
        desc: Follow us on Twitter to get the latest news!

      - name: Linkedin
        url: 'https://www.linkedin.com/company/mezmo'
        icon: fab fa-linkedin
        desc: Practical questions and curated answers

    developer:
      - name: GitHub
        url: 'https://github.com/logdna'
        icon: fab fa-github
        desc: Development takes place here!

#      - name: Slack
#        url: 'https://example.org/slack'
#        icon: fab fa-slack
#        desc: Chat with other project developers

#      - name: Developer mailing list
#        url: 'https://example.org/mail'
#        icon: fa fa-envelope
#        desc: Discuss development issues around the project

menus:
  main:
    - identifier: Workshops
      name: Workshops
      weight: 10

    - name: Java PetClinic
      parent: Workshops
      url: /pet-clinic
      weight: 1


    - name: Edge Financial Transaction to S3
      parent: Workshops
      url: /transaction-to-s3
      weight: 2
      
#    - name: Examples
#      url: "/examples/"
#      pre: "<i class='fas fa-certificate'></i>"
#      weight: 13


permalinks:
  blog: '/:section/:year/:month/:day/:slug/'

imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart

languages:
  en:
    title: Mezmo Workshops
    description: Workshops for understanding Mezmo Observability Cloud
    languageName: English
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4

    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    # https://atelierbram.github.io/syntax-highlighting/prism/demo/
#    style: tango
#    style: native
#    style: manni
#    style: monokai
#    style: ghcolors
#    style: hopscotch

  # Control the depth of the right hand TOC
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2

outputs:
  section:
    - HTML
    - print
    - RSS

module:
  hugoVersion:
    extended: true
    min: 0.75.0
  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false
